### ISSUE TITLE
Hash is not calculated correctly

### ISSUE THREAD

**Issue by jaruba** [aetheon/node-opensubtitles-client#17]
I'm trying to use your node implementation for the OpenSubtitles API.

I need to calculate the hash of partially downloaded files. I tested this extensively in attempts to understand the issue better.

I used ```console.log()``` with the file hash on every new chunk of data that was added to the file.

Throughout the download procedure, I get these 3 hashes (in order of how much they appeared):

    // this one is the most frequent, it appears in 95% of the checks but has only 2 subtitle results
    c94693cfc5b4232e

    // this one appeared very rarely, mostly at the start and the end of the download
    // and is clearly an error of some sort
    5d9ffe3e

    // this one appeared only 2-3 times at the start and has the most results! (27)
    ca2273c784db626a

The strange thing is, after the file has completely downloaded, I checked the hash a few times again, just to make sure. And although ```c94693cfc5b4232e``` was the result most of the times, ```5d9ffe3e``` still appeared a few times.

Both ```c94693cfc5b4232e``` and ```ca2273c784db626a``` give correct subtitles for the video, but ```ca2273c784db626a``` is clearly the better one and is almost never calculated.

**Comment by jaruba** [comment]
I've tested this extensively in attempts to understand the issue better.

I used ```console.log()``` with the file hash on every new chunk of data that was added to the file.

Throughout the download procedure, I get these 3 hashes (in order of how much they appeared):

    c94693cfc5b4232e (this one is the most frequent, it appears in 90% of the checks)
    5d9ffe3e
    ca2273c784db626a

The strange thing is, after the file has completely downloaded, I checked the hash a few times again, just to make sure. And although ```c94693cfc5b4232e``` was the result most of the times, ```5d9ffe3e``` still appeared a few times. Also, ```c94693cfc5b4232e``` is the one with the least results. (only 2 subtitles)

I'm really scratching my head on this one..

**Comment by jaruba** [comment]
Tested again, this time ```ca2273c784db626a``` was never calculated. :(

**Comment by aetheon** [comment]
@jaruba I need to take a look on the hash generation.

About the partially file I'm afraid that's not possible because the algorithm to calculate the hash uses 
information from the begin and end of the file, so if you don't have the full file it will not work. 
( http://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes )

**Comment by jaruba** [comment]
I'm using https://github.com/mafintosh/peerflix which downloads the first and last part of the files first in order for vlc to get some required data too. Your module seems to get (what it thinks is) the correct hash after about 20% (sometimes even 10-15% of the file).

This node module works to get the correct hash: https://github.com/ka2er/node-opensubtitles-api

**Comment by jaruba** [comment]
Also, how many bytes of data does it actually need from the start and end of the file? I might be able to modify https://github.com/mafintosh/torrent-stream to get those bytes first too, as I already know the correct file size from the start.

**Comment by 2ge** [comment]
there is correct hash sourcecode for JS here http://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#Javascript

**Comment by PauloLuan** [comment]
Check out these two projects, both have the algorithm for calculating the hash:

https://github.com/blazvi/osdb-hash
https://github.com/ka2er/node-opensubtitles-api

**Comment by aetheon** [comment]
@2ge Will try that next week.

**Comment by aetheon** [comment]
@jaruba Applied https://github.com/ka2er/node-opensubtitles-api algorithm. available on npm v2.1. Thanks for the tips.
