### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by jaruba** [aetheon/node-opensubtitles-client#18]
If I try to logout, I get "results is not defined".

I believe that this code:

    function(response){
        dfd.resolve(results);
    });

Should be changed to:

    function(response){
        dfd.resolve(response);
    });

In [API.js](https://github.com/aetheon/node-opensubtitles-client/blob/master/lib/API.js) at the ```API.prototype.logout``` function.

**Comment by aetheon** [comment]
@ziacik NPM v1.4.0 should fix your problem.
